apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-python
  labels:
    serving.knative.dev/visibility: cluster-local  

spec:
  template:
    spec:
      containers:
      - image: docker.io/ccarnero/kopa-hello-python:latest
        livenessProbe:
          httpGet:
            path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz

