apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: hosted-services.kernel.madcloud.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kernel.madcloud.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name: # distintos nombres para la misma img de ECR
                  type: string
                imageRepository:
                  type: string
                tag:
                  type: string
                minScale:
                  type: integer
                  default: 0
                visibility:
                  type: string
                envs:
                  type: array
                  maxItems: 20
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
              required:
                - name
                - imageRepository
            status:
             type: object
             description: HostedServiceStatus defines the observed state of HostedService
             properties:
              hostedServiceState:
                type: string
      subresources:
        status: {}
      # The columns we see in the kubectl output.
      additionalPrinterColumns:
      - name: Name
        type: string
        description: The service name
        jsonPath: .spec.name
      - name: ImageRepository
        type: string
        description: Docker image repository path
        jsonPath: .spec.imageRepository
      - name: tag
        type: string
        description: tag to deploy/deployed
        jsonPath: .status.tag
      - name: age
        type: date
        description: Age
        jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: hosted-services
    singular: hosted-service
    kind: HostedService
    shortNames:
    - gm
