apiVersion: kernel.madcloud.io/v1
kind: HostedService
metadata:
  name: pong 
spec:
  name: pong # redundante, ver como darle buena forma a esto
  imageRepository: docker.io/villardl/pong
  tag: "latest"
  # visibility: "internal"