apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pong
  namespace: talbots-production
  labels:
    app.kubernetes.io/name: pong
    # networking.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      imagePullSecrets:
        - name: ecr-credential-secrets
      containers:
        - image: 701373377822.dkr.ecr.us-east-1.amazonaws.com/talbots/pong
          ports:
            - containerPort: 8080
