apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-auth-opa-client-svc
  namespace: knative-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-auth-opa-client-svc
  template:
    metadata:
      labels:
        app: ext-auth-opa-client-svc
    spec:
      containers:
      - image: docker.io/ccarnero/ext_auth_opa_client_svc:latest
        name: ext-auth-opa-client-svc
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ext-auth-opa-client-svc
  namespace: knative-serving
spec:
  type: ClusterIP
  selector:
    app: ext-auth-opa-client-svc
  ports:
  - name: http
    port: 8080
    protocol: TCP